print("문자열 출력 방법")
print('문자열 출력방법')
print("I'm fine, thanks you!")
print("I\"m fine, thanks you!")
print("번호       이름      사는곳")
print("1        김혜인     광주")
print("2        정용범     용인")
print("3        김혜원     서울")
print("1\t\t김혜인\t\t광주")
print("2\t\t정용범\t\t용인")
print("3\t\t김혜원\t\t서울")